build-job:
  stage: build
  script:
    - echo "Hello from your local machine, $GITLAB_USER_LOGIN!"

test-job:
  stage: test
  script:
    - echo "Running tests locally on this runner..."

deploy-prod:
  stage: deploy
  script:
    - echo "Simulating production deployment from the $CI_COMMIT_BRANCH branch."
  environment: production
